///|
pub fn light() -> JadeTheme {
  {
    primary: "oklch(45% 0.24 277.023)",
    primaryContent: "oklch(93% 0.034 272.788)",
    secondary: "oklch(65% 0.241 354.308)",
    secondaryContent: "oklch(94% 0.028 342.258)",
    accent: "oklch(77% 0.152 181.912)",
    accentContent: "oklch(38% 0.063 188.416)",
    neutral: "oklch(14% 0.005 285.823)",
    neutralContent: "oklch(92% 0.004 286.32)",
    base100: "oklch(100% 0 0)",
    base200: "oklch(98% 0 0)",
    base300: "oklch(95% 0 0)",
    baseContent: "oklch(21% 0.006 285.885)",
    info: "oklch(74% 0.16 232.661)",
    infoContent: "oklch(29% 0.066 243.157)",
    success: "oklch(76% 0.177 163.223)",
    successContent: "oklch(37% 0.077 168.94)",
    warning: "oklch(82% 0.189 84.429)",
    warningContent: "oklch(41% 0.112 45.904)",
    error: "oklch(71% 0.194 13.428)",
    errorContent: "oklch(27% 0.105 12.094)",
    radiusSelector: "0.5rem",
    radiusField: "0.25rem",
    radiusBox: "0.5rem",
    sizeSelector: "0.25rem",
    sizeField: "0.25rem",
    border: "1px"
  }
}
